### PR TITLE
Fix use in dependant/grandchildren types

### PR DESCRIPTION
**Pull request by hwiedPro**
## Changes
- Fix create_xtypes_project.py
- Fix building of projects that depend on xtypes by the xtypes::... syntax
- Adds support to depend on xtypes::... in inherit
- Ensure proper namespacing (esp. for python modules)
  - Fixes python usage for grandchildren packages
  - Fix class inheritance in python
  - [Breaking Change] XType is no longer part of the inherent packages but xtypes_generator_py only.

All classes exist only in the package where they are defined.
Nevertheless they are true children of their parent class even if the parent class is from another package.

## Tests
I ran the following tests:
- xtypes_generator:
  - cpp_test -> succeeds
  - py_test -> not available
- xtypes:
  - cpp_test -> fails with the following issue, but I'm not sure whether this is my fault, @m0rsch1 
     ```
     /home/henning.wiedemann/yaro_dev/base/types/xtypes/test/unit_tests.cpp:894: FAILED:
    due to a fatal error condition:
      SIGSEGV - Segmentation violation signal
    ```
  - py_test -> fails as expected as the following change is required in dfki-ric/xtypes:
    ```diff
    diff --git a/test/test_xtypes_componentModel.py b/test/test_xtypes_componentModel.py
    index 8ea5e7f..2218ed1 100644
    --- a/test/test_xtypes_componentModel.py
    +++ b/test/test_xtypes_componentModel.py
    @@ -1,5 +1,6 @@
     import unittest
    -from xtypes_py import ComponentModel, InterfaceModel, XType, Component, ProjectRegistry
    +from xtypes_generator_py import XType
    +from xtypes_py import ComponentModel, InterfaceModel, Component, ProjectRegistry
     
     
     class TestComponentModel(unittest.TestCase):
    ```
- I created a test child package that depends on xtypes_generator and xtypes and that creates and builds successfully. The python import looks as wanted.

## Sources:
I found this quite heplful for the inheritance in pybind: https://pybind11.readthedocs.io/en/stable/advanced/misc.html#partitioning-code-over-multiple-extension-modules

### CODE REVIEW

**Comment by m0rsch1** [comment]
Do we also have to change the manifest.xml generation? Or is this already ok?

**Comment by hwiedPro** [comment]
> Do we also have to change the manifest.xml generation? Or is this already ok?

The manifest is not yet generated. Which will also be difficult as xtypes_generator is not always in representation. ;)

**Comment by m0rsch1** [comment]
Den SEGFAULT im cpp_test kann ich nicht reproduzieren

**Comment by m0rsch1** [comment]
Adapted xtypes (same branch name) py_test to these changes

**Comment by m0rsch1** [comment]
For me this branch works in our current setup. However there are still open points in the review above.

**Pull request merged**
